### ISSUE TITLE
Dataset taxa check script

### ISSUE THREAD

**Issue by egrace479** [Imageomics/open_clip#11]
Write script to add to [TreeOfLife10M Creation Process](https://github.com/Imageomics/open_clip/blob/main/docs/imageomics/treeoflife10m.md#how-to-create-treeoflife-10m) that checks for holes in taxonomy which should have been filled. This will serve as a final spot-check a la the [ToL EDA notebook](https://huggingface.co/datasets/imageomics/ToL-EDA/blob/main/notebooks/ToL_EDA.ipynb).

**Comment by thompsonmj** [comment]
Since the title of this task covers more than just hole-checking, I'll add that we should make use of [opentree](https://pypi.org/project/opentree/) library for taxonomic data quality checks.
